package io.vanillabp.camunda8.quarkus.runtime;

import java.util.Map;

import io.vanillabp.camunda8.client.Camunda8ClientFactoryRegistry;
import io.vanillabp.camunda8.deployment.Camunda8DeploymentService;
import io.vanillabp.camunda8.processservice.Camunda8ProcessService;
import io.vanillabp.integration.adapter.migration.config.MigrationAdapterProperties;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Produces;

/**
 * Provides the Camunda 8 adapter's {@link Camunda8ProcessService} as a CDI bean picked
 * up by the process service beans generated by the VanillaBP Quarkus integration. The
 * adapter ID is resolved from the configuration (first adapter of type
 * {@code camunda8}).
 */
@ApplicationScoped
public class Camunda8ProcessServiceProducer {

  @Produces
  public Camunda8ProcessService<Object> camunda8MigratableProcessService(
      final MigrationAdapterProperties properties,
      final Camunda8ClientFactoryRegistry clientFactoryRegistry) {

    final var adapterId = properties
        .getAdapters()
        .entrySet()
        .stream()
        .filter(adapter -> Camunda8DeploymentService.ADAPTER_TYPE.equals(adapter.getValue()))
        .map(Map.Entry::getKey)
        .findFirst()
        .orElse("");

    return new Camunda8ProcessService<>(
        adapterId, clientFactoryRegistry.getFactory(adapterId));

  }

}
