package io.vanillabp.camunda8.quarkus.deployment;

import io.quarkus.arc.deployment.AdditionalBeanBuildItem;
import io.quarkus.deployment.annotations.BuildProducer;
import io.quarkus.deployment.annotations.BuildStep;
import io.quarkus.deployment.builditem.FeatureBuildItem;
import io.vanillabp.camunda8.deployment.Camunda8DeploymentService;
import io.vanillabp.camunda8.quarkus.deployment.config.Camunda8Properties;
import io.vanillabp.camunda8.quarkus.runtime.Camunda8ClientProducer;
import io.vanillabp.camunda8.quarkus.runtime.Camunda8DeploymentServiceProducer;
import io.vanillabp.camunda8.quarkus.runtime.Camunda8ProcessServiceProducer;
import io.vanillabp.integration.deployment.processservice.VanillaBpMigratableProcessServiceBuildItem;

/**
 * Quarkus extension of the VanillaBP Camunda 8 adapter. Announces the adapter type and
 * its process-service bean to the VanillaBP Quarkus integration and registers the
 * runtime producer.
 */
class Camunda8IntegrationProcessor {

  private static final String FEATURE = "vanillabp-camunda8";

  /**
   * Builds the {@link VanillaBpMigratableProcessServiceBuildItem} used by the VanillaBP
   * Quarkus integration to determine the process-service class of the Camunda 8
   * adapter.
   *
   * @param properties Camunda 8 build-time properties
   * @param featureProducer Feature build-item producer used to register the extension
   * @return The {@link VanillaBpMigratableProcessServiceBuildItem}
   */
  @BuildStep
  VanillaBpMigratableProcessServiceBuildItem buildProcessServices(
      final Camunda8Properties properties,
      final BuildProducer<FeatureBuildItem> featureProducer) {

    featureProducer.produce(new FeatureBuildItem(FEATURE));

    return VanillaBpMigratableProcessServiceBuildItem
        .builder()
        .adapterType(Camunda8DeploymentService.ADAPTER_TYPE)
        // the announced bean class is registered by the VanillaBP extension - it
        // has to be the producer, not the core process-service class
        .migratableProcessServiceBeanClass(Camunda8ProcessServiceProducer.class.getName())
        .build();

  }

  /**
   * Registers the producer of the Camunda 8 adapter's process-service bean picked up by
   * the process-service beans generated by the VanillaBP Quarkus integration.
   *
   * @return The bean registration build item
   */
  @BuildStep
  AdditionalBeanBuildItem registerProcessServiceProducer() {

    // the process-service producer is registered by the VanillaBP extension via
    // the build item above - only the other producers are registered here
    return AdditionalBeanBuildItem
        .builder()
        .addBeanClass(Camunda8ClientProducer.class)
        .addBeanClass(Camunda8DeploymentServiceProducer.class)
        .setUnremovable()
        .build();

  }

}
